const PDFDocument = require('pdfkit');

/**
 * src/utils/pdfkitGenerator.js
 * Generates a professional PDF report using PDFKit.
 */
exports.generateReport = (report) => {
    return new Promise((resolve, reject) => {
        const doc = new PDFDocument({ margin: 50 });
        let buffers = [];

        doc.on('data', buffers.push.bind(buffers));
        doc.on('end', () => {
            let pdfData = Buffer.concat(buffers);
            resolve(pdfData);
        });

        const { type, report_id, data, created_at } = report;

        // 1. Header
        doc.fillColor('#1e1b4b').fontSize(20).text('CHURN INTELLIGENCE AUDIT', { align: 'center' });
        doc.fontSize(10).fillColor('#64748b').text(`REPORT ID: ${report_id} | ${new Date(created_at).toLocaleString()}`, { align: 'center' });
        doc.moveDown(2);

        // 2. Title
        doc.fillColor('#6366f1').fontSize(16).text(type.replace('_', ' ').toUpperCase(), { underline: true });
        doc.moveDown();

        // 3. Summary Metrics
        if (data.summary) {
            doc.fillColor('#1e1b4b').fontSize(14).text('Summary Metrics');
            doc.moveDown(0.5);
            doc.fontSize(12).fillColor('#334155');
            doc.text(`Total Users: ${data.summary.total_users}`);
            doc.text(`Churn Rate: ${(data.summary.churn_rate * 100).toFixed(1)}%`);
            doc.text(`Retention Rate: ${(data.summary.retention_rate * 100).toFixed(1)}%`);
            doc.text(`High Risk Users: ${data.summary.high_risk_users}`);
            doc.moveDown();
        }

        // 4. Strategic Insights
        doc.fillColor('#1e1b4b').fontSize(14).text('Strategic Insights');
        doc.moveDown(0.5);
        doc.fontSize(10).fillColor('#475569');
        
        const insights = data.patterns || (data.recommendations ? data.recommendations.map(r => r.action) : ["No specific insights available."]);
        
        insights.forEach((insight, i) => {
            doc.text(`${i + 1}. ${insight}`);
            doc.moveDown(0.2);
        });

        // 5. Footer
        doc.fontSize(10).fillColor('#94a3b8').text('Generated by AI Agentic Intelligence Engine', 50, 750, { align: 'center' });

        doc.end();
    });
};
